name: CI Pipeline

on: push  # Runs the workflow on every push

jobs:
  build:
    runs-on: ubuntu-latest  # The OS environment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Pulls your repo code

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies  # Speeds up builds
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}

      - name: Build and Run Tests with Maven
        run: mvn clean test  # Runs test cases

      - name: Upload Test Reports
        if: always()  # Runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: target/surefire-reports/  # Default Maven test report location
