name: CI Pipeline

on: push  # Runs the workflow on every push

jobs:
  test:
    runs-on: ubuntu-latest  # Run on Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pulls latest code

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        run: mvn test  # Executes all test cases
